# Generated by Django 3.2 on 2022-07-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220722_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
